// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Author information for the notebook document.
 */
export type Author = {
  /**
   * Name of the author.
   */
  name?: string;
};
