// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to clear output visible on the frontend.
 */
export type ClearOutput = {
  /**
   * Wait to clear the output until new output is available to replace it.
   */
  wait: boolean;
};
