// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Represents the CodeMirror mode, which could be a string or a nested object.
 */
export type CodeMirrorMode = string | { [key in string]?: JsonValue };
