// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellMetadata } from "./CellMetadata";
import type { MultilineString } from "./MultilineString";
import type { Output } from "./Output";

/**
 * Code cell in the notebook.
 */
export type CodeCell = {
  /**
   * Identifier of the cell.
   */
  id?: string;
  /**
   * Metadata for the cell.
   */
  metadata: CellMetadata;
  /**
   * Content of the cell.
   */
  source: MultilineString;
  /**
   * Execution count of the cell (null if not executed).
   */
  execution_count: number | null;
  /**
   * Outputs from executing the cell.
   */
  outputs: Array<Output>;
};
