// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultilineString } from "./MultilineString";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Display data output.
 */
export type DisplayData = {
  /**
   * Data to display.
   */
  data: { [key in string]?: MultilineString };
  /**
   * Metadata associated with the display data.
   */
  metadata: { [key in string]?: JsonValue };
};
