// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transient data associated with display data, such as display IDs.
 */
export type DisplayDataTransient = {
  /**
   * Specifies an ID for the display, which can be updated.
   */
  display_id: string | null;
};
