// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonBTreeMap } from "./JsonBTreeMap";
import type { MultilineString } from "./MultilineString";

/**
 * Display data output.
 */
export type DisplayData = { 
/**
 * Data to display.
 */
data: { [key in string]?: MultilineString }, 
/**
 * Metadata associated with the display data.
 */
metadata: JsonBTreeMap, };
