// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayDataTransient } from "./DisplayDataTransient";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Data to be displayed in frontends, such as images or HTML.
 */
export type DisplayData = {
  /**
   * The data to be displayed, typically a MIME type and the data itself.
   */
  data: { [key in string]?: JsonValue };
  /**
   * Metadata associated with the data, can be empty.
   */
  metadata: { [key in string]?: JsonValue };
  /**
   * Any information not to be persisted to a notebook.
   */
  transient: DisplayDataTransient | null;
};
