// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Results of a code execution, such as the output or return value.
 */
export type ExecuteResult = {
  /**
   * The execution count, which increments with each request that stores
   * history.
   */
  execution_count: number;
  /**
   * The data to be displayed, typically a MIME type and the data itself. A
   * plain text representation should always be provided in the `text/plain`
   * mime-type.
   */
  data: { [key in string]?: JsonValue };
  /**
   * Metadata associated with the data, can be empty.
   */
  metadata: { [key in string]?: JsonValue };
};
