// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A simple newtype around `BTreeMap<String, Value>` so we can give it a TS type.
 */
export type JsonBTreeMap = Record<string, unknown>;
