// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kernel specification metadata.
 */
export type KernelSpec = { 
/**
 * Name of the kernel specification.
 */
name: string, 
/**
 * Display name of the kernel.
 */
display_name: string, };
