// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KernelMessageType } from "./KernelMessageType";

/**
 * Header of a message, generally part of the {header, parent_header, metadata,
 * content, buffers} 5-tuple.
 */
export type KernelHeader = {
  /**
   * Typically UUID, must be unique per message.
   */
  msg_id: string;
  /**
   * Typically UUID, should be unique per session.
   */
  session: string;
  /**
   * The username of the user sending the message.
   */
  username: string;
  /**
   * ISO 8601 timestamp for when the message is created.
   */
  date: string;
  /**
   * The message type.
   */
  msg_type: KernelMessageType;
  /**
   * Message protocol version.
   */
  version: string;
};
