// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of a kernel wire protocol message, either request or reply.
 */
export type KernelMessageType =
  | "execute_request"
  | "execute_reply"
  | "inspect_request"
  | "inspect_reply"
  | "complete_request"
  | "complete_reply"
  | "history_request"
  | "history_reply"
  | "is_complete_request"
  | "is_complete_reply"
  | "comm_info_request"
  | "comm_info_reply"
  | "kernel_info_request"
  | "kernel_info_reply"
  | "shutdown_request"
  | "shutdown_reply"
  | "interrupt_request"
  | "interrupt_reply"
  | "debug_request"
  | "debug_reply"
  | "stream"
  | "display_data"
  | "update_display_data"
  | "execute_input"
  | "execute_result"
  | "error"
  | "status"
  | "clear_output"
  | "debug_event"
  | string;
