// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a string or array of strings (multiline).
 */
export type MultilineString = string | Array<string>;
