// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./Author";
import type { KernelSpec } from "./KernelSpec";
import type { LanguageInfo } from "./LanguageInfo";

/**
 * Root-level metadata for the notebook.
 */
export type NotebookMetadata = {
  /**
   * Kernel information.
   */
  kernelspec?: KernelSpec;
  /**
   * Programming language information.
   */
  language_info?: LanguageInfo;
  /**
   * Original notebook format before conversion.
   */
  orig_nbformat?: number;
  /**
   * Title of the notebook document.
   */
  title?: string;
  /**
   * Authors of the notebook document.
   */
  authors?: Array<Author>;
};
