// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputDisplayData } from "./OutputDisplayData";
import type { OutputError } from "./OutputError";
import type { OutputExecuteResult } from "./OutputExecuteResult";
import type { OutputStream } from "./OutputStream";

/**
 * Output from executing a code cell.
 */
export type Output =
  | ({ output_type: "execute_result" } & OutputExecuteResult)
  | ({ output_type: "display_data" } & OutputDisplayData)
  | ({ output_type: "stream" } & OutputStream)
  | ({ output_type: "error" } & OutputError);
