// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultilineString } from "./MultilineString";

/**
 * Stream output.
 */
export type OutputStream = {
  /**
   * Name of the stream (e.g., stdout or stderr).
   */
  name: string;
  /**
   * Text content of the stream.
   */
  text: MultilineString;
};
