// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Result of executing a code cell.
 */
export type OutputExecuteResult = {
  /**
   * Execution count of the result.
   */
  execution_count: number | null;
  /**
   * Data returned by the execution.
   */
  data: { [key in string]?: JsonValue };
  /**
   * Metadata associated with the result.
   */
  metadata: { [key in string]?: JsonValue };
};
