// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayData } from "./DisplayData";
import type { ErrorOutput } from "./ErrorOutput";
import type { ExecuteResult } from "./ExecuteResult";
import type { Stream } from "./Stream";

/**
 * Output from executing a code cell.
 */
export type Output =
  | ({ output_type: "execute_result" } & ExecuteResult)
  | ({ output_type: "display_data" } & DisplayData)
  | ({ output_type: "stream" } & Stream)
  | ({ output_type: "error" } & ErrorOutput);
