// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error output.
 */
export type OutputError = {
  /**
   * Name of the error.
   */
  ename: string;
  /**
   * Value or message of the error.
   */
  evalue: string;
  /**
   * Traceback of the error.
   */
  traceback: Array<string>;
};
