// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayData } from "./DisplayData";
import type { ErrorReply } from "./ErrorReply";
import type { ExecuteResult } from "./ExecuteResult";

/**
 * Events that can be received while running a cell.
 */
export type RunCellEvent =
  | { event: "stdout"; data: string }
  | { event: "stderr"; data: string }
  | { event: "execute_result"; data: ExecuteResult }
  | { event: "display_data"; data: DisplayData }
  | { event: "update_display_data"; data: DisplayData }
  | { event: "error"; data: ErrorReply }
  | { event: "disconnect"; data: string };
